import Foundation

struct QuoteProvider {
    static let quotes = [
        "The secret of getting ahead is getting started.",
        "The best time to plant a tree was 20 years ago. The second best time is now.",
        "It's not whether you get knocked down, it's whether you get up.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream bigger. Do bigger.",
        "Don't stop when you're tired. Stop when you're done.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Do something today that your future self will thank you for.",
        "Little things make big days.",
        "It's going to be a great day!",
        "The future depends on what you do today.",
        "Believe you can and you're halfway there.",
        "The only way to do great work is to love what you do.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "You are never too old to set another goal or to dream a new dream.",
        "The road to success is always under construction.",
        "Act as if what you do makes a difference. It does.",
        "The difference between ordinary and extraordinary is that little extra.",
        "You have to expect things of yourself before you can do them.",
        "It does not matter how slowly you go as long as you do not stop.",
        "The key to success is to focus on goals, not obstacles.",
        "Well done is better than well said.",
        "The expert in anything was once a beginner.",
        "Be so good they can't ignore you.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "I find that the harder I work, the more luck I seem to have.",
        "Opportunities don't happen, you create them.",
        "Don't be afraid to give up the good to go for the great.",
        "If you are not willing to risk the usual, you will have to settle for the ordinary.",
        "All our dreams can come true, if we have the courage to pursue them.",
        "If you want to achieve greatness stop asking for permission.",
        "Things work out best for those who make the best of how things work out.",
        "To live a creative life, we must lose our fear of being wrong.",
        "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
        "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Don't let yesterday take up too much of today.",
        "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
        "It’s not about having time. It’s about making time.",
        "A goal is a dream with a deadline.",
        "Either you run the day or the day runs you.",
        "The question isn’t who is going to let me; it’s who is going to stop me.",
        "Everything you’ve ever wanted is on the other side of fear.",
        "Hard work beats talent when talent doesn’t work hard.",
        "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.",
        "I am not a product of my circumstances. I am a product of my decisions.",
        "The most difficult thing is the decision to act, the rest is merely tenacity.",
        "The best revenge is massive success.",
        "I have not failed. I've just found 10,000 ways that won't work.",
        "If you're going through hell, keep going.",
        "What seems to us as bitter trials are often blessings in disguise.",
        "The distance between insanity and genius is measured only by success.",
        "Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you.",
        "I will not lose, for even in defeat, there’s a valuable lesson learned, so it evens up for me.",
        "The starting point of all achievement is desire.",
        "Success is the sum of small efforts, repeated day-in and day-out.",
        "All progress takes place outside the comfort zone.",
        "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.",
        "Courage is resistance to fear, mastery of fear - not absence of fear.",
        "Only put off until tomorrow what you are willing to die having left undone.",
        "People often say that motivation doesn't last. Well, neither does bathing -- that's why we recommend it daily."
    ]

    static func getRandomQuote() -> String {
        quotes.randomElement() ?? "You got this!"
    }
}
